# Generated by Django 4.2.7 on 2023-11-21 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pontos',
            fields=[
                ('PontoID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='apiTT.city')),
            ],
        ),
    ]
