# Generated by Django 4.2.7 on 2023-11-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pontos',
            new_name='Ponto',
        ),
    ]
