# Generated by Django 4.2.7 on 2023-11-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0002_rename_pontos_ponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='Local',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='Maps',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
