# Generated by Django 4.2.7 on 2023-11-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0004_alter_ponto_local_alter_ponto_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='Local',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='Maps',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
