# Generated by Django 4.2.7 on 2023-11-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0006_rename_city_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='Local',
            new_name='Endereco',
        ),
    ]
