# Generated by Django 4.2.7 on 2023-11-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0007_rename_local_ponto_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('InfoId', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
