# Generated by Django 4.2.7 on 2023-11-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0008_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Texto',
            field=models.TextField(default=None),
        ),
    ]
