# Generated by Django 4.2.7 on 2023-11-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0005_alter_ponto_local_alter_ponto_maps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Cidade',
        ),
    ]
