# Generated by Django 4.2.7 on 2023-11-23 22:22

import apiTT.models.slide
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0011_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('IMG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Imagem', models.ImageField(upload_to=apiTT.models.slide.nome_img)),
                ('Conteudo', models.CharField(default='Imagem<django.db.models.fields.AutoField>', max_length=100)),
            ],
        ),
    ]
