# Generated by Django 4.2.7 on 2023-11-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0014_alter_slide_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='Conteudo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
