# Generated by Django 4.2.7 on 2023-11-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0015_alter_slide_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='Endereco',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='Maps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pontofisico',
            name='Endereco',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='pontofisico',
            name='Maps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
