from .CidadeView import CidadeRetrieveUpdateDestroyView, CidadeListCreateView
from .SlideView import SlideRetrieveUpdateDestroyView, SlideListCreateView
from .PontosFisicosView import PontoFisicoRetrieveUpdateDestroyView, PontoFisicoListCreateView
from .InfoView import InfoRetrieveUpdateDestroyView, InfoListCreateView
from .ContatoView import ContatoListCreateView, ContatoRetrieveUpdateDestroyView
from .home import home