# Generated by Django 4.2.7 on 2023-11-22 23:51

import apiTT.models.PontosFisicos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0009_info_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoFisico',
            fields=[
                ('PF_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Imagem', models.ImageField(upload_to=apiTT.models.PontosFisicos.nome_imagem)),
                ('Endereco', models.CharField(max_length=400)),
                ('Maps', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
