# Generated by Django 4.2.7 on 2023-11-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0010_pontofisico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('ContatoID', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('telefone', 'Telefone'), ('email', 'Email')], max_length=10)),
                ('Conteudo', models.CharField(max_length=100)),
            ],
        ),
    ]
