# Generated by Django 4.2.7 on 2023-11-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTT', '0012_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='Conteudo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
